### PR TITLE
Global command arguments

### PR DESCRIPTION
**Pull request by jcredding**
This effort started with @tpett's commits to limit memory globally on pruview commands.  There is now a global configuration, `GLOBAL_CMD_ARGS`, that is applied to every command Pruview executes.

### CODE REVIEW

**Comment by jcredding** [comment]
@kellyredding These should be straight from Travis' repo. Let me know if you want anything else done. Also, let me know when you roll a new version and I'll update our usage.

**Comment by kellyredding** [comment]
@jcredding - you good with the rename I did?  If so, I'll roll a new version.

@tpett - heads up and thanks for the commits.

**Comment by jcredding** [comment]
@kellyredding works for me, makes sense calling them global

**Comment by kellyredding** [comment]
@jcredding - rolled v0.3.0 with these updates.

**Pull request merged**
